from app.models import academic_year  # noqa: F401
from app.models import announcement  # noqa: F401
from app.models import assignment  # noqa: F401
from app.models import attendance  # noqa: F401
from app.models import complaint  # noqa: F401
from app.models import conversation  # noqa: F401
from app.models import document  # noqa: F401
from app.models import exam  # noqa: F401
from app.models import exam_schedule  # noqa: F401
from app.models import fee  # noqa: F401
from app.models import feedback  # noqa: F401
from app.models import gallery  # noqa: F401
from app.models import homework  # noqa: F401
from app.models import homework_submission  # noqa: F401
from app.models import jti_blocklist  # noqa: F401
from app.models import leave_balance  # noqa: F401
from app.models import masters  # noqa: F401
from app.models import message  # noqa: F401
from app.models import notification  # noqa: F401
from app.models import otp_store  # noqa: F401
from app.models import parent  # noqa: F401
from app.models import payment  # noqa: F401
from app.models import permission  # noqa: F401
from app.models import result  # noqa: F401
from app.models import role  # noqa: F401
from app.models import role_permission  # noqa: F401
from app.models import school  # noqa: F401
from app.models import school_settings  # noqa: F401
from app.models import student  # noqa: F401
from app.models import student_academic_history  # noqa: F401
from app.models import student_behaviour_log  # noqa: F401
from app.models import student_diary  # noqa: F401
from app.models import submission  # noqa: F401
from app.models import teacher  # noqa: F401
from app.models import teacher_class_subject  # noqa: F401
from app.models import teacher_leave  # noqa: F401
from app.models import timetable  # noqa: F401
from app.models import user  # noqa: F401
